# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_date', models.DateTimeField(verbose_name='data de publicacao')),
                ('tweet_user', models.CharField(max_length=15)),
                ('tweet_cidade', models.CharField(max_length=50)),
                ('tweet_pais', models.CharField(max_length=50)),
                ('tweet_nchar', models.IntegerField(default=0)),
                ('tweet_nwords', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TweetText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(max_length=150)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweeter.Tweet')),
            ],
        ),
    ]
