# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_text',
            field=models.CharField(default='', max_length=150),
        ),
    ]
