# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0002_tweet_tweet_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_user',
            field=models.CharField(max_length=50),
        ),
    ]
