# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0004_tweetspordata_tweetsporlocal_tweetsporuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetsporlocal',
            name='data',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='tweetsporuser',
            name='data',
            field=models.DateField(default=None),
        ),
    ]
