# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0005_auto_20160128_2213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TweetsPorLocal',
            new_name='TweetsLocal',
        ),
        migrations.RenameModel(
            old_name='TweetsPorUser',
            new_name='TweetsUser',
        ),
    ]
