# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0007_auto_20160128_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_date',
            field=models.DateField(verbose_name='data de publicacao'),
        ),
    ]
